root: true

parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - ./tsconfig.json

env:
  node: true
  mocha: true

plugins:
  - "@typescript-eslint"
  - prettier

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended

rules:
  prettier/prettier: [error, {}, {usePrettierrc: true}]
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-non-null-assertion": off

  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: none
  "@typescript-eslint/semi": off
  eol-last: error
  indent: [error, 2, {SwitchCase: 1}]
  quotes: [error, double]
  no-var: error
  spaced-comment:
    - error
    - always