name: CI

on:
  workflow_dispatch:
    
  push:
    branches:
      - "**"

jobs:
  runUnitTests:
    uses: valenciadb/.github/.github/workflows/nodejs-ci.yaml@main
    with:
      setupAntlr4: true

  runIntegrationTests:
    name: Node.js ${{ matrix.node }} on $ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: runUnitTests

    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]

    services:
      redis:
        image: redislabs/rejson
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Set up Antlr4
        uses: siacodelabs/setup-antlr4@v1
      
      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci -ws --include-workspace-root
      
      - name: Build
        run: npm run build
      
      - name: Run integration tests
        run: npm run test/itg
