name: ci

on:
  workflow_dispatch:
    
  push:
    branches:
      - "**"
    paths:
      - "**.js"
      - "**.json"
      - "**/.mocha.rc"

permissions:
  contents: read

jobs:
  unit-tests:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Set up Gattuso
        uses: akromio/setup-gattuso@v1
      
      - name: Set up Antlr4
        uses: siacodelabs/setup-antlr4@v2
      
      - name: Install dependencies
        run: npm ci -ws --include-workspace-root
      
      - name: Static code analysis
        run: npm run lint

      - name: Build
        run: npm run build
      
      - name: Run unit tests
        run: npm run cov
